# Generated by Django 3.2.12 on 2022-03-25 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='名称')),
                ('sort', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('description', models.TextField(default='', verbose_name='描述')),
                ('liaisons', models.JSONField(default=list, verbose_name='联系人列表')),
                ('stages', models.JSONField(default=list, verbose_name='阶段策略列表')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policies.level', verbose_name='奖项级别')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
