# Generated by Django 3.2.12 on 2022-03-28 11:59

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models

import bk_award.awards.constants


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicants', models.JSONField(default=list, verbose_name='申请人或团队列表')),
                ('status', models.CharField(choices=[('started', '申报中'), ('failed', '未获奖'), ('succeed', '已获奖')], default=bk_award.awards.constants.ApplicationStatus['STARTED'], max_length=32, verbose_name='状态')),
                ('liaisons', models.JSONField(default=list, verbose_name='申报接口人列表')),
                ('staffs', models.JSONField(default=list, verbose_name='项目成员')),
                ('details', models.JSONField(default=dict, verbose_name='申报详情')),
            ],
            options={
                'db_table': 'award_application',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='名称')),
                ('sort', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'award_level',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('status', models.CharField(choices=[('pending', '未开始'), ('started', '进行中'), ('finished', '完成'), ('aborted', '中止')], default=bk_award.awards.constants.StageStatus['PENDING'], max_length=32, verbose_name='状态')),
                ('details', models.JSONField(default=dict, verbose_name='阶段详情')),
                ('started_at', models.DateTimeField(verbose_name='开始时间')),
                ('ended_at', models.DateTimeField(verbose_name='截止时间')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='awards.application', verbose_name='申请')),
            ],
            options={
                'db_table': 'award_stage',
            },
            managers=[
                ('generator', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('type', models.CharField(max_length=32, verbose_name='类型')),
                ('details', models.JSONField(verbose_name='详情')),
                ('status', models.CharField(choices=[('pending', '未开始'), ('started', '进行中'), ('finished', '完成'), ('aborted', '中止')], default=bk_award.awards.constants.StageStatus['PENDING'], max_length=32, verbose_name='状态')),
                ('started_at', models.DateTimeField(verbose_name='开始时间')),
                ('ended_at', models.DateTimeField(verbose_name='截止时间')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='awards.stage', verbose_name='阶段')),
            ],
            options={
                'db_table': 'award_step',
            },
            managers=[
                ('generator', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('description', models.TextField(default='', verbose_name='描述')),
                ('liaisons', models.JSONField(default=list, verbose_name='联系人列表')),
                ('stages', models.JSONField(default=list, verbose_name='阶段策略列表')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awards.level', verbose_name='奖项级别')),
            ],
            options={
                'db_table': 'award_policy',
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, verbose_name='奖项名称')),
                ('description', models.TextField(verbose_name='奖项描述')),
                ('year', models.IntegerField(default=0, verbose_name='年份')),
                ('quarter', models.IntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')], verbose_name='季度')),
                ('status', models.CharField(choices=[('pending', '未开始'), ('started', '可申报'), ('expired', '已过期')], max_length=32, verbose_name='状态')),
                ('started_at', models.DateTimeField(verbose_name='开始时间')),
                ('ended_at', models.DateTimeField(verbose_name='截止时间')),
                ('liaisons', models.JSONField(default=list, verbose_name='联系人列表')),
                ('orgs', models.JSONField(default=list, verbose_name='关联组织 ID 列表')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='awards.policy', verbose_name='奖项策略')),
            ],
            options={
                'db_table': 'award_award',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='award',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='awards.award', verbose_name='奖项'),
        ),
    ]
