# Generated by Django 2.2.6 on 2022-02-21 13:59
import os

from awards_apply.models import Admin
from django.db import migrations


def init_admin(apps, schema_editor):
    try:
        admin_list = ["admin", "kaisheng", "wheellong"]
        admin_list += os.getenv("admin").split(",") if os.getenv("admin") else []
        admin_instance_list = [Admin(admin_username=item) for item in admin_list]
        Admin.objects.bulk_create(admin_instance_list)
    except Exception as e:
        print(u'数据初始化错误: {}'.format(e))


class Migration(migrations.Migration):

    dependencies = [
        ('awards_apply', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(init_admin)
    ]
