# Generated by Django 2.2.6 on 2022-03-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards_apply', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.IntegerField(verbose_name='申请id')),
                ('department_id', models.IntegerField(verbose_name='组id')),
                ('approval_time', models.DateTimeField(auto_now_add=True, verbose_name='审批时间')),
                ('approval_user', models.CharField(max_length=100, verbose_name='审批人')),
                ('approval_action', models.IntegerField(choices=[(0, '未通过'), (1, '通过')], verbose_name='审批操作')),
            ],
        ),
    ]
