# Generated by Django 2.2.6 on 2022-03-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards_apply', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupapply',
            unique_together={('group_id', 'username')},
        ),
        migrations.AlterUniqueTogether(
            name='groupuser',
            unique_together={('group_id', 'username')},
        ),
        migrations.CreateModel(
            name='GroupInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('group_id', models.IntegerField(verbose_name='组id')),
                ('username', models.CharField(max_length=128, verbose_name='受邀成员')),
            ],
            options={
                'unique_together': {('group_id', 'username')},
            },
        ),
    ]
