# Generated by Django 2.2.6 on 2022-01-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards_apply', '0002_auto_20220119_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secretary',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='secretary',
            name='level',
        ),
        migrations.RemoveField(
            model_name='secretary',
            name='parent',
        ),
        migrations.AddField(
            model_name='awards',
            name='award_department_fullname',
            field=models.CharField(default=1, max_length=50, verbose_name='奖项所属部门full_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secretary',
            name='group_full_name',
            field=models.CharField(default='s', max_length=50, verbose_name='组full_name'),
            preserve_default=False,
        ),
    ]
