# Generated by Django 2.2.6 on 2022-03-23 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards_apply', '0002_auto_20220321_2339'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupapply',
            unique_together=set(),
        ),
    ]
