# Generated by Django 2.2.6 on 2022-03-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards_apply', '0002_auto_20220221_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='award_image',
            field=models.CharField(max_length=1000, verbose_name='图片地址'),
        ),
    ]
