# Generated by Django 2.2.6 on 2022-01-20 06:17

import django_mysql.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards_apply', '0003_auto_20220120_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardapplicationrecord',
            name='application_attachments',
            field=django_mysql.models.JSONField(default=list, verbose_name='申请附件地址列表'),
        ),
        migrations.AlterField(
            model_name='awardapplicationrecord',
            name='application_users',
            field=django_mysql.models.JSONField(default=list, verbose_name='申请人username列表'),
        ),
        migrations.AlterField(
            model_name='secretary',
            name='secretaries',
            field=django_mysql.models.JSONField(default=list, verbose_name='组内秘书'),
        ),
    ]
