# Generated by Django 2.2.6 on 2022-03-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards_apply', '0003_auto_20220304_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardapplicationrecord',
            name='approval_text',
            field=models.TextField(default='', verbose_name='评审评语'),
        ),
    ]
