# Generated by Django 2.2.6 on 2022-03-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards_apply', '0003_auto_20220323_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupapply',
            name='group_name',
            field=models.CharField(max_length=128, verbose_name='组名字'),
        ),
    ]
