# Generated by Django 2.2.6 on 2022-01-27 15:11

import django_mysql.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards_apply', '0004_auto_20220120_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awardapplicationrecord',
            name='approval_user',
        ),
        migrations.AddField(
            model_name='awardapplicationrecord',
            name='approval_users',
            field=django_mysql.models.JSONField(default=dict, null=True, verbose_name='评审人map'),
        ),
        migrations.AddField(
            model_name='awards',
            name='award_reviewers',
            field=django_mysql.models.JSONField(default=list, verbose_name='奖项评委'),
        ),
    ]
