# Generated by Django 2.2.6 on 2022-03-07 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards_apply', '0004_auto_20220304_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
    ]
