# Generated by Django 2.2.6 on 2022-02-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards_apply', '0005_auto_20220127_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardapplicationrecord',
            name='approval_turn',
            field=models.IntegerField(default=1, verbose_name='评审轮次'),
        ),
    ]
