# Generated by Django 2.2.6 on 2022-02-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards_apply', '0006_awardapplicationrecord_approval_turn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardapplicationrecord',
            name='approval_turn',
            field=models.IntegerField(default=0, verbose_name='评审轮次'),
        ),
    ]
