# Generated by Django 2.2.6 on 2022-03-19 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards_apply', '0007_auto_20220318_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupapply',
            name='approver',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='审批人账号'),
        ),
        migrations.AlterField(
            model_name='groupapply',
            name='approver_display_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='审批人姓名'),
        ),
    ]
